/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bookline;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Danish
 */
public class borrowing extends javax.swing.JFrame {

    /**
     * Creates new form borrowing
     */
    public borrowing() {
        initComponents();
        buku();
    }

    String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
    //alamat lokasi database yang digunakan lihat dari service yang dibuat
    String url = "jdbc:sqlserver://localhost\\LAPTOP-R1312I9E\\MSSQLSERVER02:1433;databaseName=db_perpus_online;encrypt=true;trustServerCertificate=true;";
    // login user ke database
    String username = "danish";
    // login password ke database
    String password = "123"; 
    //https://docs.oracle.com/javase/7/docs/api/java/sql/Statement.html
    Statement st=null;
    //https://docs.oracle.com/javase/7/docs/api/java/sql/ResultSet.html
    ResultSet rs=null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtsearch = new javax.swing.JTextField();
        txtBook = new javax.swing.JTextField();
        txtNim = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        txtReturn = new com.toedter.calendar.JDateChooser();
        txtBorrowing = new com.toedter.calendar.JDateChooser();
        txtLibrarian = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        searchbtn = new javax.swing.JButton();
        txtQty = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 0));
        jLabel1.setText("BORROWING");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(314, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 60);

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.setLayout(null);
        jPanel2.add(txtsearch);
        txtsearch.setBounds(290, 10, 260, 30);
        jPanel2.add(txtBook);
        txtBook.setBounds(80, 80, 260, 30);
        jPanel2.add(txtNim);
        txtNim.setBounds(80, 132, 260, 30);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Book Name", "Publisher", "Writer", "date of issues"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 230, 740, 250);
        jPanel2.add(txtReturn);
        txtReturn.setBounds(510, 190, 260, 30);
        jPanel2.add(txtBorrowing);
        txtBorrowing.setBounds(510, 130, 260, 30);
        jPanel2.add(txtLibrarian);
        txtLibrarian.setBounds(510, 80, 260, 30);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("NIM");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(80, 110, 90, 20);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("QTY");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(80, 170, 40, 20);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel6.setText("Return  date");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(510, 170, 110, 20);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel7.setText("Book Id");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(80, 60, 90, 20);

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel8.setText("Librarian Name");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(510, 60, 110, 20);

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel9.setText("Borrowing date");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(510, 110, 110, 20);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(760, 400, 75, 30);

        jButton2.setBackground(new java.awt.Color(0, 204, 51));
        jButton2.setText("add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(760, 250, 72, 30);

        jButton4.setBackground(new java.awt.Color(0, 204, 51));
        jButton4.setText("update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(760, 450, 75, 30);

        jButton5.setBackground(new java.awt.Color(255, 0, 0));
        jButton5.setText("delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(760, 300, 75, 30);

        searchbtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        jPanel2.add(searchbtn);
        searchbtn.setBounds(220, 10, 72, 30);

        txtQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyActionPerformed(evt);
            }
        });
        jPanel2.add(txtQty);
        txtQty.setBounds(80, 190, 260, 30);

        jButton6.setBackground(new java.awt.Color(0, 204, 51));
        jButton6.setText("next");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(760, 350, 75, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 60, 900, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public void buku()
       {
            DefaultTableModel tbl_pr = new DefaultTableModel();
        tbl_pr.addColumn("Book Id");
        tbl_pr.addColumn("Book Name");
         tbl_pr.addColumn("Publisher");
          tbl_pr.addColumn("Writer");
          tbl_pr.addColumn("Date of issues");
         table.setModel(tbl_pr);

           try {
                        Class.forName(driver);

            Connection con = DriverManager.getConnection(url,username,password);
            st = con.createStatement();
            rs = st.executeQuery("select * from dbo.tbl_data_buku ");
            while(rs.next()){
                tbl_pr.addRow(new Object[]{
                    rs.getString("id_buku"),
                    rs.getString("judul_buku"),
                    rs.getString("tahun_terbit"),
                    rs.getString("status_buku"),
                    rs.getString("penerbit"),
                    rs.getString("penulis")

                
                });
               
            }
            table.setModel(tbl_pr);
           } catch (Exception e) {
                           JOptionPane.showMessageDialog(null, "data gagal");

           }
        
       
       }

    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          try {
        String Snim = txtNim.getText();
        String SBookId = txtBook.getText();
        String Sqty = txtQty.getText();
        int  qty = Integer.parseInt(Sqty);
        SimpleDateFormat dcn = new SimpleDateFormat("yyyy-MM-dd");
        String Sdateborrowing = String.valueOf(dcn.format(txtBorrowing.getDate()));
       String Sdatereturn = String.valueOf(dcn.format(txtReturn.getDate()));  
        String SLibrarian_name =txtLibrarian.getText();
      
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url,username,password);
            String sql ="insert into tbl_Pinjam_buku ( id_buku, nim, jumlah_buku, tgl_pinjam, tgl_kembali, nama_pustakawan) values ('"+SBookId+"','"+Snim+"','"+qty+"', '"+Sdateborrowing+"', '"+Sdatereturn+"', '"+SLibrarian_name+"')";

            st = con.createStatement();
            st.execute(sql);
            buku();
            JOptionPane.showMessageDialog(this, "Insert Succesfully");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        DefaultTableModel   model_det = (DefaultTableModel)table.getModel();
//        String id_sp = (String) model_det.getValueAt(row, 0);
//        String names = (String) model_det.getValueAt(row, 1);
//        
//        String Sharga = (String) model_det.getValueAt(row, 3);
//        String Koharga = Sharga.replace(".","");
//        String Nolharga = Koharga.substring(0, Koharga.length()-4);
//        txtNames.setText(names);
//        txtPrice.setText(Nolharga);
//        txtIdPr.setText(id_sp);
            txtBook.setText(model_det.getValueAt(row, 0).toString());       
    }//GEN-LAST:event_tableMouseClicked

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String BookId=  txtBook.getText();
         try {
            
             Class.forName(driver);
            Connection con = DriverManager.getConnection(url,username,password);
                        String sql ="delete from dbo.tbl_Pinjam_buku where id_buku =  '"+BookId+"'";

            
            st = con.createStatement();
            st.execute(sql);
             buku();
            JOptionPane.showMessageDialog(this, "Delete successfully");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
           String BookId =  txtBook.getText();
           String NIM = txtNim.getText();
           String Sqty = txtQty.getText();
           int  qty = Integer.parseInt(Sqty);
           SimpleDateFormat dcn = new SimpleDateFormat("yyyy-MM-dd");
           String Sdateborrowing = String.valueOf(dcn.format(txtBorrowing.getDate()));
           String Sdatereturn = String.valueOf(dcn.format(txtReturn.getDate()));  
           String SLibrarian_name =txtLibrarian.getText();
          
            
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url,username,password);
            String sql ="update tbl_Pinjam_buku set id_buku  = '"+BookId+"', nim = '"+NIM+"', jumlah _buku = '"+qty+"', tgl_pinjam = '"+Sdateborrowing+"', tgl_kembali = '"+Sdatereturn+"', nama_pustakawan = '"+SLibrarian_name+"' ";
                        
            st = con.createStatement();
            st.execute(sql);
                                    buku();

                        JOptionPane.showMessageDialog(this, "Update successfully");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tabModel = new DefaultTableModel(new Object []{"tbl_data_buku"},0);
     try{
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url,username,password);
            String query = "SELECT * FROM tbl_data_buku WHERE Id_buku like '%" + txtsearch.getText() + "%' OR judul_buku like '%" + txtsearch.getText() + "%' OR penulis like '%" + txtsearch.getText()+"%'"; 
            rs = st.executeQuery(query);
            while (rs.next()){
                tabModel.addRow(new Object[]{rs.getString("Id_buku"),rs.getString("judul_buku"), rs.getString("penulis")});
            }
            table.setModel(tabModel);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }    // TODO add your ha
    }//GEN-LAST:event_searchbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        home hm = new home();
        hm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        list_borrow lbr = new list_borrow();
        lbr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(borrowing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(borrowing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(borrowing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(borrowing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new borrowing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtBook;
    private com.toedter.calendar.JDateChooser txtBorrowing;
    private javax.swing.JTextField txtLibrarian;
    private javax.swing.JTextField txtNim;
    private javax.swing.JTextField txtQty;
    private com.toedter.calendar.JDateChooser txtReturn;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
