/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bookline;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Danish
 */
public class list_borrow extends javax.swing.JFrame {

    /**
     * Creates new form list_borrow
     */
    public list_borrow() {
        initComponents();
        buku();
        pengembalian();
    }
       String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
    //alamat lokasi database yang digunakan lihat dari service yang dibuat
    String url = "jdbc:sqlserver://localhost\\LAPTOP-R1312I9E\\MSSQLSERVER02:1433;databaseName=db_perpus_online;encrypt=true;trustServerCertificate=true;";
    // login user ke database
    String username = "danish";
    // login password ke database
    String password = "123"; 
    //https://docs.oracle.com/javase/7/docs/api/java/sql/Statement.html
    Statement st=null;
    //https://docs.oracle.com/javase/7/docs/api/java/sql/ResultSet.html
    ResultSet rs=null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblreturn = new javax.swing.JTable();
        borrowid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        StatusRadio = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblbuku = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.setLayout(null);

        tblreturn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "return id", "Borrowing Id", "Status", "Return Date"
            }
        ));
        tblreturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblreturnMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblreturn);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(280, 240, 750, 190);
        jPanel2.add(borrowid);
        borrowid.setBounds(30, 260, 170, 22);

        jLabel5.setText("Status");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 290, 100, 16);

        jRadioButton1.setText("NOT");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton1);
        jRadioButton1.setBounds(90, 310, 98, 21);

        StatusRadio.setText("Done");
        StatusRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusRadioActionPerformed(evt);
            }
        });
        jPanel2.add(StatusRadio);
        StatusRadio.setBounds(30, 310, 80, 21);

        jButton1.setBackground(new java.awt.Color(0, 204, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jButton1.setText("add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(120, 360, 75, 40);

        tblbuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Borrowing id", "Book Id", "NIM", "QTY", "Borrowing Date", "Return Date"
            }
        ));
        tblbuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbukuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblbuku);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(20, 20, 1020, 200);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel7.setText("Borrowing Id");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(30, 240, 100, 16);

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jButton3.setText("back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(30, 360, 75, 40);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 0));
        jLabel1.setText("LIST BORROWING");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(jLabel1)
                .addContainerGap(296, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1042, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 626, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(66, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(33, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblbukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbukuMouseClicked
        // TODO add your handling code here:
        int row = tblreturn.getSelectedRow();
        DefaultTableModel   model_det = (DefaultTableModel)tblreturn.getModel();
        //        String id_sp = (String) model_det.getValueAt(row, 0);
        //        String names = (String) model_det.getValueAt(row, 1);
        //
        //        String Sharga = (String) model_det.getValueAt(row, 3);
        //        String Koharga = Sharga.replace(".","");
        //        String Nolharga = Koharga.substring(0, Koharga.length()-4);
        //        txtNames.setText(names);
        //        txtPrice.setText(Nolharga);
        //        txtIdPr.setText(id_sp);
        borrowid.setText(model_det.getValueAt(row, 0).toString());
    }//GEN-LAST:event_tblbukuMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            String SBookId = borrowid.getText();
            int bookid = Integer.parseInt(SBookId);
            String status = "";
            if(StatusRadio.isSelected())
            {
                status = "done";
            }
            else
            {
                status = "done";
            }
                String Created_at = new SimpleDateFormat("yyyy.MM.dd").format(new java.util.Date());
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url,username,password);
            String sql ="insert into tbl_pengembalian ( id_pinjam, status_pengembalian, tgl_pengembalian) values ('"+bookid+"','"+status+"', '"+Created_at+"')";

            st = con.createStatement();
            st.execute(sql);
            buku();
            JOptionPane.showMessageDialog(this, "Insert Succesfully");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void StatusRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusRadioActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void tblreturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblreturnMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_tblreturnMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        home hm = new home();
        hm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    public void pengembalian()
       {
          
           
        DefaultTableModel tbl_pr = new DefaultTableModel();
        tbl_pr.addColumn("return id");
        tbl_pr.addColumn("Borrowing id");
         tbl_pr.addColumn("Status");
         tbl_pr.addColumn("Return Date");
        tblreturn
                .setModel(tbl_pr);

           try {
                        Class.forName(driver);

            Connection con = DriverManager.getConnection(url,username,password);
            st = con.createStatement();
            rs = st.executeQuery("select * from dbo.tbl_pengembalian");
            while(rs.next()){
                tbl_pr.addRow(new Object[]{
                          rs.getString("id_pengembalian"),
                    rs.getString("id_pinjam"),
                    rs.getString("status_pengembalian"),
                    rs.getString("tgl_pengembalian")

                
                });
               
            }
            tblreturn.setModel(tbl_pr);
           } catch (Exception e) {
                           JOptionPane.showMessageDialog(null, "data gagal");

           }
       }
    
    public void buku()
       {
          
           
        DefaultTableModel tbl_pr = new DefaultTableModel();
        tbl_pr.addColumn("Borrowing id");
        tbl_pr.addColumn("Book Id");
        tbl_pr.addColumn("NIM");
         tbl_pr.addColumn("QTY");
          tbl_pr.addColumn("Borrowing Date");
          tbl_pr.addColumn("Return Date");
        tblbuku.setModel(tbl_pr);

           try {
                        Class.forName(driver);

            Connection con = DriverManager.getConnection(url,username,password);
            st = con.createStatement();
            rs = st.executeQuery("select * from dbo.tbl_pinjam_buku ");
            while(rs.next()){
                tbl_pr.addRow(new Object[]{
                          rs.getString("id_pinjam"),
                    rs.getString("id_buku"),
                    rs.getString("nim"),
                    rs.getString("jumlah_buku"),
                    rs.getString("tgl_pinjam"),
                    rs.getString("tgl_kembali")

                
                });
               
            }
            tblbuku.setModel(tbl_pr);
           } catch (Exception e) {
                           JOptionPane.showMessageDialog(null, "data gagal");

           }
        
}
        
                
               
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(list_borrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(list_borrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(list_borrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(list_borrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new list_borrow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton StatusRadio;
    private javax.swing.JTextField borrowid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblbuku;
    private javax.swing.JTable tblreturn;
    // End of variables declaration//GEN-END:variables
}
